#!/bin/bash

# download tmux plugin manager
# https://github.com/tmux-plugins/tpm
# Install plugins by launching tmux and `prefix + I`.
if [ ! -d $HOME/.tmux/plugins/tpm ]; then
    mkdir -p $HOME/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
